server:
  port: 8081

mobius-rpc:
  zkServer: localhost:2181
  zkRoot: mobius-rpc

app:
  id: app1
  namespace: public
  env: dev


logging:
  level:
    root: error
    com.prayerlaputa.mobiusrpc: info