server:
  port: 8088

mobius-rpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2181
  zkRoot: mobius-rpc


app:
  id: app1
  namespace: public
  env: dev

logging:
  level:
    root: error
    com.prayerlaputa.mobiusrpc: info